command = "transmission.sh list"
interval = 1

[keybindings]
"p" = "transmission.sh add"
"f" = "transmission.sh file"
"l" = "transmission.sh start"
"h" = "transmission.sh stop"
"x" = "transmission.sh remove"
"X" = "transmission.sh delete"
