#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
polybar.sh &
feh --no-fehbg --bg-scale ~/.wallpapers/macos_mojave_night.jpg &

bspc config border_width 2
bspc config window_gap 1
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#8FAAC9"

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspwm-rule-floating.sh

bspc rule -a Zathura state=tiled focus=on desktop=any.!occupied
bspc rule -a discord desktop=any.!occupied
bspc rule -a mpv desktop=any.!occupied
bspc rule -a Slack desktop=any.!occupied
